- Changed help and a few options

diff --git a/scripts/updstats/dbs_updstats b/scripts/updstats/dbs_updstats
--- a/scripts/updstats/dbs_updstats
+++ b/scripts/updstats/dbs_updstats
@@ -10,13 +10,15 @@
 
 
 PROGNAME=`basename $0`
-VERSION="1.2"
+VERSION=`echo "$Revision$" | cut -f2 -d' '`
 
 show_help()
 {
-	printf "${PROGNAME}: { -d database } [ -f filter ] [ -e |  -E file] [ -p priority ]\n[ -P | -N ] [ -r resolution ] [ -c confidence ] [ -T ] [ -s ] [ -x | -X ] [ -y ] [ -z | -Z ]\n" >&2
-	echo "               -d database (required)" >&2
-	echo "               -f table filter (optional)" >&2
+	printf "${PROGNAME}: -V | -h | { -d database } [ -f filter ] [ -e |  -E file] [ -p priority ]\n[ -P | -N ] [ -r resolution ] [ -c confidence ] [ -T ] [ -s ] [ -x | -X ] [ -y ] [ -z | -Z ]\n" >&2
+	echo "               {-d database} (required)" >&2
+	echo "               {-f table} filter (optional)" >&2
+	echo "               [-h] Show help and exit">&2
+	echo "               [-V] Show version and exit">&2
 	echo "               [-e] Set explain on (versions >= 7.31.UD2 and 9.30.UC2)" >&2
 	echo "               [-E file] Set explain to a file (versions >= 11.10)" >&2
 	echo "               [-p priority] Set pdqpriority (versions >= 7.31.UD2 and 9.30.UC2)" >&2
@@ -37,7 +39,7 @@ show_help()
 
 get_args()
 {
-	arg_ok='p:d:f:r:c:E:ePNvhTsyxXzZ'
+	arg_ok='p:d:f:r:c:E:ePNVhTsyxXzZ'
 	list="$*"
 	getopt ${arg_ok} $list >/dev/null 2>&1
 	# check result of parsing                                                
@@ -54,7 +56,7 @@ get_args()
 			show_help
 			exit 0
 			;;
-		-v)   # show version
+		-V)   # show version
 			echo "${PROGNAME} version ${VERSION}" >&1
 			exit 0
 			;;
@@ -127,7 +129,7 @@ get_args()
 			then
 				return
 			fi
-			arg_ok='p:d:f:r:c:E:ePNvhTsyxXzZ'
+			arg_ok='p:d:f:r:c:E:ePNVhTsyxXzZ'
 			set -- `getopt "${arg_ok}" $resto`
 			continue
 			;;
@@ -327,7 +329,7 @@ get_args()
 					then
 						return
 					fi
-					arg_ok='p:d:f:r:c:E:ePNvhTsyxXzZ'
+					arg_ok='p:d:f:r:c:E:ePNVhTsyxXzZ'
 					set -- `getopt "${arg_ok}" $resto`
 					continue
 			fi;;
diff --git a/scripts/updstats/tbl_updstats b/scripts/updstats/tbl_updstats
--- a/scripts/updstats/tbl_updstats
+++ b/scripts/updstats/tbl_updstats
@@ -30,14 +30,16 @@ export DELIMIDENT
 
 show_help()
 {
-	echo "${PROGNAME}: { [-d] database } { [-t] table } [ -e | -E file ] [ -p priority ] [ -r resolution ] [ -c confidence ] [ -x|X ] [ -T ]" >&2
-	echo "               [-d] database (required)" >&2
-	echo "               [-t] table (required)" >&2
-	echo "               [-p] Set PDQPRIORITY (versions >= a 7.31.UD2 and 9.30.UC2)" >&2
-	echo "               [-r] Set resolution" >&2
-	echo "               [-c] Set confidence" >&2
+	echo "${PROGNAME}: -h | -V | { [-d] database } { [-t] table } [ -e | -E file ] [ -p priority ]\n[ -r resolution ] [ -c confidence ] [ -x|X ] [ -T ]" >&2
+	echo "               { [ -d ] database } (required)" >&2
+	echo "               { [-t] table}  (required)" >&2
+	echo "               [-h] Show help and exit">&2
+	echo "               [-V] Show version and exit" >&2
+	echo "               [-p] Set PDQPRIORITY (versions >= 7.31.UD2 and 9.30.UC2)" >&2
+	echo "               [-r resolution] Set resolution" >&2
+	echo "               [-c confidence] Set confidence" >&2
 	echo "               [-e] Set explain on (versions >= 7.31.UD2 and 9.30.UC2)" >&2
-	echo "               [-E] file Set explain file (versions >= 11.10)" >&2
+	echo "               [-E file ] Set explain file (versions >= 11.10)" >&2
 	echo "               [-X] Display and execute" >&2
 	echo "               [-x] Display only. Don't execute" >&2
 	echo "               [-T] Include timings in de SQL generated" >&2
@@ -46,7 +48,7 @@ show_help()
 
 get_args()
 {
-	arg_ok="d:t:p:r:c:E:hevTxX"
+	arg_ok="d:t:p:r:c:E:heVTxX"
 	list="$*"
 	getopt ${arg_ok} $list >/dev/null 2>&1
 	# check result of parsing                                                
