- Added options to FORCE and define STATCHANGE

diff --git a/scripts/updstats/dbs_updstats b/scripts/updstats/dbs_updstats
--- a/scripts/updstats/dbs_updstats
+++ b/scripts/updstats/dbs_updstats
@@ -2,50 +2,52 @@
 # Copyright (c) 2001-2016 Fernando Nunes - domusonline@gmail.com
 # License: This script is licensed as GPL V2 ( http://www.gnu.org/licenses/old-licenses/gpl-2.0.html )
 # $Author: Fernando Nunes - domusonline@gmail.com $
-# $Revision 2.0.1 $
-# $Date 2016-02-22 02:38:48$
+# $Revision: 2.0.39 $
+# $Date: 2018-04-03 17:28:33 $
 # Disclaimer: This software is provided AS IS, without any kind of guarantee. Use at your own risk.
 #             Although the author is/was an IBM employee, this software was created outside his job engagements.
 #             As such, all credits are due to the author.
 # This script runs the tbl_updstats script for each table in the database
 
 PROGNAME=`basename $0`
-VERSION=`echo "$Revision 2.0.1 $" | cut -f2 -d' '`
+VERSION=`echo "$Revision: 2.0.39 $" | cut -f2 -d' '`
 
 show_help()
 {
-	printf "${PROGNAME}: -V | -h | { -d database } [ -f filter ] [ -e |  -E file] [ -p priority ]\n[ -P | -N ] [ -m size ] [ -r resolution ] [ -c confidence ] [ -R resolution ] [ -T ] [ -s ] [-l ] [ -x | -X ] [ -y ] [ -z | -Z ] [ -i | -I {table_list_file} ]\n" >&2
-	echo "               {-d database} (required)" >&2
-	echo "               [-f filter ] Additional filters to restrict tables" >&2
-	echo "               [-h] Show help and exit">&2
-	echo "               [-V] Show version and exit">&2
-	echo "               [-e] Set explain on (versions >= 7.31.UD2 and 9.30.UC2)" >&2
-	echo "               [-i table_list_file] run for the tables contained in file" >&2
-	echo "               [-I table_list_file] run without the tables contained in file" >&2
-	echo "               [-E file] Set explain to a file (versions >= 11.10)" >&2
-	echo "               [-p priority] Set pdqpriority (versions >= 7.31.UD2 and 9.30.UC2)" >&2
-	echo "               [-P] Updates statistics for procedures also (default without filter)" >&2
-	echo "               [-N] Don't update statistics for procedures (default with filter)" >&2
-	echo "               [-r resolution] Set resolution for MEDIUM distributions" >&2
-	echo "               [-c confidence] Set confidence" >&2
-	echo "               [-m size] Set minimum sample size (versions >= 11.10)">&2
-	echo "               [-R resolution] Set resolution for HIGH distributions" >&2
-	echo "               [-l] Use quick LOW mode (Avoid b-tree leaf scan. Only minimal table info is collected)" >&2
-	echo "               [-T] Include timings" >&2
-	echo "               [-s] Include system catalog tables" >&2
-	echo "               [-x] Option for tbl_updstats. Display only. Do not execute" >&2
-	echo "               [-X] Option for tbl_updstats. Display and execute".>&2
-	echo "               [-z] Display only. Do not execute" >&2
-	echo "               [-Z] Display and execute" >&2
-	echo "               [-y] Allow multiple parallel executions">&2
-	echo "               [-o] Specify user for tbl_updstats (ANSI databases)">&2
-	echo "               [-w N ] Set LOCK MODE WAIT N seconds">&2
-	echo "Ex: dbs_updstats -d stores7 -f \\\" and tabname like \\'l%\\'\\\"" >&2
+	printf "${PROGNAME}: -V | -h | { -d database } [ -f filter ] [ -e |  -E file] [ -p priority ]\n[ -P | -N ] [ -m size ] [ -r resolution ] [ -c confidence ] [ -R resolution ] [ -T ] [ -s ] [-l ] [ -x | -X ] [ -y ] [ -z | -Z ] [ -F | -S {stat_change} ] [ -i | -I {table_list_file} ]\n"
+	echo "               {-d database} (required)"
+	echo "               [-f filter ] Additional filters to restrict tables"
+	echo "               [-h] Show help and exit"
+	echo "               [-V] Show version and exit"
+	echo "               [-e] Set explain on (versions >= 7.31.UD2 and 9.30.UC2)"
+	echo "               [-i table_list_file] run for the tables contained in file"
+	echo "               [-I table_list_file] run without the tables contained in file"
+	echo "               [-E file] Set explain to a file (versions >= 11.10)"
+	echo "               [-p priority] Set pdqpriority (versions >= 7.31.UD2 and 9.30.UC2)"
+	echo "               [-P] Updates statistics for procedures also (default without filter)"
+	echo "               [-N] Don't update statistics for procedures (default with filter)"
+	echo "               [-r resolution] Set resolution for MEDIUM distributions"
+	echo "               [-c confidence] Set confidence"
+	echo "               [-m size] Set minimum sample size (versions >= 11.10)"
+	echo "               [-R resolution] Set resolution for HIGH distributions"
+	echo "               [-l] Use quick LOW mode (Avoid b-tree leaf scan. Only minimal table info is collected)"
+	echo "               [-T] Include timings"
+	echo "               [-s] Include system catalog tables"
+	echo "               [-x] Option for tbl_updstats. Display only. Do not execute"
+	echo "               [-X] Option for tbl_updstats. Display and execute"
+	echo "               [-z] Display only. Do not execute"
+	echo "               [-Z] Display and execute"
+	echo "               [-y] Allow multiple parallel executions"
+	echo "               [-o] Specify user for tbl_updstats (ANSI databases)"
+	echo "               [-w N ] Set LOCK MODE WAIT N seconds"
+	echo "               [-F] to force statistics even if AUTO_STAT_MODE is on"
+	echo "               [-S stat_change] to define a STATCHANGE value and work in AUTO mode"
+	echo "Ex: dbs_updstats -d stores7 -f \\\" and tabname like \\'l%\\'\\\""
 }
 
 get_args()
 {
-	arg_ok='p:d:f:m:r:R:c:E:lePNVhTsyxXzZow:i:I:'
+	arg_ok='p:d:f:m:r:R:c:E:lePNVhTsyxXzZow:i:I:FS:'
         while getopts ${arg_ok} OPTION
         do
                 case ${OPTION} in
@@ -146,9 +148,24 @@ get_args()
 		o)   # set up the -o (ANSI user flag)
 			ANSI_USER_FLAG=1
 			;;
-		S)   # set SET SESSION AUTH flag
-			SET_AUTH_FLAG=1
-			SET_AUTH_USER=${OPTARG}
+		F)   # FORCE mode
+			if [ "X${STATCHANGE_FLAG}" != "X" ]
+			then
+				echo "${PROGNAME} Syntax error: Option -F cannot be used with -S" >&2
+				return 1
+			else
+				FORCE_FLAG=1
+			fi
+			;;
+		S)   # STATCHANGE option
+			if [ "X${FORCE_FLAG}" != "X" ]
+			then
+				echo "${PROGNAME} Syntax error: Option -S cannot be used with -F" >&2
+				return 1
+			else
+				STATCHANGE_FLAG=1
+				STATCHANGE_VALUE=${OPTARG}
+			fi
 			;;
 		w)   # set up the -w (LOCK WAIT flag)
 			LOCK_MODE_FLAG=1
@@ -171,6 +188,10 @@ get_args()
 				echo "${PROGNAME} Syntax error: Argument for option '-f' must be enclosed in quotes" >&2
 				return 1
 			esac
+			;;
+		?)   # Unlnonw option
+			return 1
+			;;
 		esac
 	done
 }
@@ -186,6 +207,7 @@ get_args $*
 if [ $? != 0 ]
 then
 	echo "${PROGNAME} Error parsing parameters" >&2
+	show_help >&2
 	exit 1
 fi
 
@@ -209,6 +231,27 @@ then
 	then
 		echo "${PROGNAME} Syntax error: PDQPRIORITY must be between 1 and 100" >&2
 		exit 1
+	fi
+fi
+
+
+if [ "X${FORCE_FLAG}" = "X1" ]
+then
+	AUTO_MODE_CLAUSE=" -F "
+else
+	if [ "X${STATCHANGE_FLAG}" = "X1" ]
+	then
+		echo ${STATCHANGE_VALUE} | grep '^[0-9]\{1,3\}$' 2>&1 >/dev/null
+		RESULT=$?
+		if [ ${RESULT} != 0 -o ${STATCHANGE_VALUE} -lt 1 -o ${STATCHANGE_VALUE} -gt 100 ]
+		then
+			echo "${PROGNAME} Syntax error: STATCHANGE value must be numeric and less than or equal to 100" >&2
+			exit 1
+		else
+			AUTO_MODE_CLAUSE=" -S ${STATCHANGE_VALUE} "
+		fi
+	else
+		AUTO_MODE_CLAUSE=" "
 	fi
 fi
 
@@ -463,7 +506,7 @@ fi
 
 if [ "X${LOCK_MODE_FLAG}" = "X1" ]
 then
-	CMD_FLAGS="${CMD_FLAGS} -w ${LOCK_MODE_TIME}"
+	CMD_FLAGS="${CMD_FLAGS} -w ${LOCK_MODE_TIME} "
 fi
 
 
@@ -483,13 +526,13 @@ do
 	case "X${DISPLAY_FLAG}" in
 	X1)
 		#--- display only...
-		echo "${COMMENT_STRING}Command: tbl_updstats -d ${dbserver} -t ${tblname} ${ANSI_USER_CLAUSE}${low_mode_flag}${resolution_clause_high}${sampling_clause}${resolution_clause_medium}${confidence_clause}${CMD_FLAGS}"
+		echo "${COMMENT_STRING}Command: tbl_updstats -d ${dbserver} -t ${tblname} ${ANSI_USER_CLAUSE}${low_mode_flag}${resolution_clause_high}${sampling_clause}${resolution_clause_medium}${confidence_clause}${AUTO_MODE_CLAUSE}${CMD_FLAGS}"
 		;;
 	X2)
 		#--- display and execute 
-		echo "${COMMENT_STRING}Command: tbl_updstats -d ${dbserver} -t ${tblname} ${ANSI_USER_CLAUSE}${low_mode_flag}${resolution_clause_high}${sampling_clause}${resolution_clause_medium}${confidence_clause}${CMD_FLAGS}"
+		echo "${COMMENT_STRING}Command: tbl_updstats -d ${dbserver} -t ${tblname} ${ANSI_USER_CLAUSE}${low_mode_flag}${resolution_clause_high}${sampling_clause}${resolution_clause_medium}${confidence_clause}${AUTO_MODE_CLAUSE}${CMD_FLAGS}"
 		cat /dev/null >${EXPLAIN_TMP_FILE}
-		tbl_updstats -d ${dbserver} -t ${tblname} ${ANSI_USER_CLAUSE}${low_mode_flag}${resolution_clause_high}${sampling_clause}${resolution_clause_medium}${confidence_clause}${CMD_FLAGS}
+		tbl_updstats -d ${dbserver} -t ${tblname} ${ANSI_USER_CLAUSE}${low_mode_flag}${resolution_clause_high}${sampling_clause}${resolution_clause_medium}${confidence_clause}${AUTO_MODE_CLAUSE}${CMD_FLAGS}
 		if [ "X${EXPLAIN_FLAG}" = "X1" ]
 		then
 			cat ${EXPLAIN_TMP_FILE} >>${explain_file}
@@ -498,7 +541,7 @@ do
 	X*)
 		#--- execute only
 		cat /dev/null >${EXPLAIN_TMP_FILE}
-		tbl_updstats -d ${dbserver} -t ${tblname} ${ANSI_USER_CLAUSE}${low_mode_flag}${resolution_clause_high}${sampling_clause}${resolution_clause_medium}${confidence_clause}${CMD_FLAGS}
+		tbl_updstats -d ${dbserver} -t ${tblname} ${ANSI_USER_CLAUSE}${low_mode_flag}${resolution_clause_high}${sampling_clause}${resolution_clause_medium}${confidence_clause}${AUTO_MODE_CLAUSE}${CMD_FLAGS}
 		if [ "X${EXPLAIN_FLAG}" = "X2" ]
 		then
 			cat ${EXPLAIN_TMP_FILE} >>${explain_file}
