- Fixes for ANSI databases - introduction of SET ISOLATION TO DIRTY READ - instroduction of SET LOCK MODE flag

diff --git a/scripts/updstats/dbs_updstats b/scripts/updstats/dbs_updstats
--- a/scripts/updstats/dbs_updstats
+++ b/scripts/updstats/dbs_updstats
@@ -36,14 +36,15 @@ show_help()
 	echo "               [-X] Option for tbl_updstats. Display and execute".>&2
 	echo "               [-z] Display only. Do not execute" >&2
 	echo "               [-Z] Display and execute" >&2
-	echo "               [-X] Display and execute" >&2
 	echo "               [-y] Allow multiple parallel executions">&2
+	echo "               [-o] Specify user for tbl_updstats (ANSI databases)">&2
+	echo "               [-w N ] Set LOCK MODE WAIT N seconds">&2
 	echo "Ex: dbs_updstats -d stores7 -f \\\" and tabname like \\'l%\\'\\\"" >&2
 }
 
 get_args()
 {
-	arg_ok='p:d:f:m:r:R:c:E:lePNVhTsyxXzZ'
+	arg_ok='p:d:f:m:r:R:c:E:lePNVhTsyxXzZow:'
 	list="$*"
 	getopt ${arg_ok} $list >/dev/null 2>&1
 	# check result of parsing                                                
@@ -131,6 +132,25 @@ get_args()
 			confidence=$2
 			shift
 			;;
+		-o)   # set up the -o (ANSI user flag)
+			ANSI_USER_FLAG=1
+			;;
+		-S)   # set SET SESSION AUTH flag
+			SET_AUTH_FLAG=1
+			SET_AUTH_USER=$2
+			shift
+			;;
+		-w)   # set up the -w (LOCK WAIT flag)
+			LOCK_MODE_FLAG=1
+			LOCK_MODE_TIME=$2
+			echo ${LOCK_MODE_TIME} | grep "^[1-9][0-9]*" >/dev/null
+			if [ $? != 0  ]
+			then
+				echo "${PROGNAME} Syntax error: LOCK WAIT time must be between a number >= 1" >&2
+				return 1
+			fi
+			shift
+			;;
 		-f)   # set up the -f (filter flag)
 			FILTER_FLAG=1
 			case $2 in
@@ -146,7 +166,7 @@ get_args()
 			then
 				return
 			fi
-			arg_ok='p:d:f:m:r:R:c:E:lePNVhTsyxXzZ'
+			arg_ok='p:d:f:m:r:R:c:E:lePNVhTsyxXzZow:'
 			set -- `getopt "${arg_ok}" $resto`
 			continue
 			;;
@@ -279,6 +299,26 @@ get_args()
 					fi
 					shift 2
 			fi;;
+		-w)
+			if [ "X"$LOCK_MODE_FLAG = "X1" ]	
+			then
+				echo "${PROGNAME} Syntax error: LOCK WAIT already processed" >&2
+				return 1
+			elif [ $# -le 1 ]
+				then
+					echo "${PROGNAME} Syntax error: Option $1 requires an argument" >&2
+					return 1
+				else
+					LOCK_MODE_FLAG=1
+					LOCK_MODE_TIME=$2
+					echo ${LOCK_MODE_TIME} | grep "^[1-9][0-9]*" >/dev/null
+					if [ $? != 0  ]
+					then
+						echo "${PROGNAME} Syntax error: LOCK WAIT time must be between a number >= 1" >&2
+						return 1
+					fi
+					shift 2
+			fi;;
 		-m)
 			if [ "X"$SAMPLING_FLAG = "X1" ]
 			then
@@ -361,9 +401,32 @@ get_args()
 						
 						echo "${PROGNAME} Syntax error: CONFIDENCE value must be between 0.80 and 0.99" >&2
 						return 1
-				fi
-				shift 2
+					fi
+					shift 2
 			fi;;
+		-S)
+			if [ "X"$SET_AUTH_FLAG = "X1" ]
+			then
+				echo "${PROGNAME} Syntax error: SET SESSION AUTH already processed" >&2
+				return 1
+			elif [ $# -le 1 ]
+				then
+					echo "${PROGNAME} Syntax error: Option $1 requires and argument" >&2
+					return 1
+				else
+					SET_AUTH_FLAG=1
+					SET_AUTH_USER=$2
+					shift 2
+			fi;;
+		o)
+			if [ "X"$ANSI_USER_FLAG = "X1" ]
+			then
+				echo "${PROGNAME} Syntax error: user flag already processed" >&2
+			else
+				ANSI_USER_FLAG=1
+			fi
+			shift
+			;;
 		-f)
 			if [ "X"$FILTER_FLAG = "X1" ]	
 			then
@@ -388,7 +451,7 @@ get_args()
 					then
 						return
 					fi
-					arg_ok='p:d:f:m:r:R:c:E:lePNVhTsyxXzZ'
+					arg_ok='p:d:f:m:r:R:c:E:lePNVhTsyxXzZow:'
 					set -- `getopt "${arg_ok}" $resto`
 					continue
 			fi;;
@@ -452,7 +515,7 @@ then
 		echo "${PROGNAME} Syntax error: RESOLUTION MEDIUM value must be numeric and less than or equal to 100" >&2
 		exit 1
 	else
-		resolution_clause_medium=" -r ${resolution_medium} "
+		resolution_clause_medium="-r ${resolution_medium} "
 	fi
 fi
 
@@ -478,7 +541,7 @@ then
 		echo "${PROGNAME} Syntax error: SAMPLING value must be numeric and greater than 0" >&2
 		exit 1
 	else
-		sampling_clause=" -m ${sampling} "
+		sampling_clause="-m ${sampling} "
 	fi
 fi
 
@@ -491,13 +554,13 @@ then
 		echo "${PROGNAME} Syntax error: CONFIDENCE must be between 0.80 and 0.99" >&2
 		exit 1
 	else
-		confidence_clause=" -c ${confidence} "
+		confidence_clause="-c ${confidence} "
 	fi
 fi
 
 if [ "X${QUICK_LOW_MODE_FLAG}" = "X1" ]
 then
-	low_mode_flag="-l"
+	low_mode_flag="-l "
 fi
 
 if [ "X"$PROCEDURES_FLAG = "X" ]
@@ -551,18 +614,47 @@ echo $$ > ${DBS_DATABASE_LOCK_FILE}
 #-----------------------------------------------------
 if [ "X${SYSTABLES_FLAG}" != "X1" ]
 then
-	sel_filter="tabid > 99 and tabtype = 'T' $sel_filter"
+	sel_filter="t.tabid > 99 and t.tabtype = 'T' $sel_filter"
 else
-	sel_filter="tabname not like ' %' and tabtype = 'T' $sel_filter"
+	sel_filter="t.tabname not like ' %' and t.tabtype = 'T' $sel_filter"
 fi
 
 
 #-----------------------------------------------------
 # obtain table list
 #-----------------------------------------------------
-dbaccess ${dbserver} - <<EOSQL 1>&2 2>${SQL_ERROR_FILE}
+if [ "X$SET_AUTH_FLAG" = "X1" ]
+then
+	SET_AUTH_CLAUSE="SET SESSION AUTHORIZATION TO '${SET_AUTH_USER}';"
+else
+	SET_AUTH_CLAUSE=""
+fi
+
+LOGGING_FLAGS=`dbaccess sysmaster - <<EOSQL 2>${SQL_ERROR_FILE} | grep "LOGGING:" | awk '{print $NF}' 
+SELECT 'LOGGING: '|| is_logging || is_ansi
+FROM sysdatabases
+WHERE name = '${dbserver}';
+EOSQL
+`
+
+case "${LOGGING_FLAGS}" in
+11|10|00)
+	LOGGING_FLAG=`echo ${LOGGING_FLAGS} | cut -c1`
+	ANSI_FLAG=`echo ${LOGGING_FLAGS} | cut -c2`
+	;;
+*)
+	echo "${PROGNAME} Error: DBACCESS error trying to check database logging mode" >&2
+	cat < ${SQL_ERROR_FILE} >&2
+	exit 1
+	;;
+esac
+	
+	
+
+dbaccess ${dbserver} - <<EOSQL 1>&2 2>${SQL_ERROR_FILE} 
+${SET_AUTH_CLAUSE}
 output to pipe "cat  | grep -v '^$' >${TABLE_LIST_FILE}" without headings
-select tabname from systables
+select trim(tabname) || ' ' ||trim(owner) from informix.systables t
 where $sel_filter
 order by 1;
 EOSQL
@@ -588,10 +680,10 @@ fi
 #-----------------------------------------------------
 case  "X$EXPLAIN_FLAG" in
 X1)
-	CMD_FLAGS="-e"
+	CMD_FLAGS="-e "
 	;;
 X2)
-	CMD_FLAGS="-E ${EXPLAIN_TMP_FILE}"
+	CMD_FLAGS="-E ${EXPLAIN_TMP_FILE} "
 	;;
 esac
 
@@ -605,27 +697,58 @@ then
 	CMD_FLAGS="${CMD_FLAGS} -T"
 fi
 
+COMMENT_STRING="#"
 if [ "X${CMD_DISPLAY_FLAG}" != "X" ]
 then
 	CMD_FLAGS="${CMD_FLAGS} ${CMD_DISPLAY_FLAG}"
+	COMMENT_STRING="--"
 fi
+
+if [ "X$SET_AUTH_FLAG" = "X1" ]
+then
+        CMD_FLAGS="${CMD_FLAGS} -S ${SET_AUTH_USER}"
+fi
+
+
+if [ "X$ANSI_FLAG" = "X1" ]
+then
+        CMD_FLAGS="${CMD_FLAGS} -i -a"
+else
+	if [ "X$LOGGING_FLAG" = "X1" ]
+	then
+	        CMD_FLAGS="${CMD_FLAGS} -i"
+	fi
+fi
+
+if [ "X${LOCK_MODE_FLAG}" = "X1" ]
+then
+	CMD_FLAGS="${CMD_FLAGS} -w ${LOCK_MODE_TIME}"
+fi
+
 
 #-----------------------------------------------------
 # Launch/display or both...
 #-----------------------------------------------------
-while read tblname
+while read tblname owner
 do
-	echo "#${PROGNAME} Processing table ${dbserver}@${INFORMIXSERVER}:${tblname} at `date` ..."
+	if [ "X$ANSI_USER_FLAG" = "X1" ]
+	then
+		ANSI_USER_CLAUSE="-o $owner "
+	else
+		ANSI_USER_CLAUSE=""
+	fi
+
+	echo "${COMMENT_STRING}${PROGNAME} Processing table ${dbserver}@${INFORMIXSERVER}:${tblname} at `date` ..."
 	case "X${DISPLAY_FLAG}" in
 	X1)
 		#--- display only...
-		echo "#Command: tbl_updstats -d ${dbserver} -t ${tblname} ${low_mode_flag} ${resolution_clause_high} ${sampling_clause} ${resolution_clause_medium} ${confidence_clause} ${CMD_FLAGS}"
+		echo "${COMMENT_STRING}Command: tbl_updstats -d ${dbserver} -t ${tblname} ${ANSI_USER_CLAUSE}${low_mode_flag}${resolution_clause_high}${sampling_clause}${resolution_clause_medium}${confidence_clause}${CMD_FLAGS}"
 		;;
 	X2)
 		#--- display and execute 
-		echo "#Command: tbl_updstats -d ${dbserver} -t ${tblname} ${low_mode_flag} ${resolution_clause_high} ${sampling_clause} ${resolution_clause_medium} ${confidence_clause} ${CMD_FLAGS}"
+		echo "${COMMENT_STRING}Command: tbl_updstats -d ${dbserver} -t ${tblname} ${ANSI_USER_CLAUSE}${low_mode_flag}${resolution_clause_high}${sampling_clause}${resolution_clause_medium}${confidence_clause}${CMD_FLAGS}"
 		cat /dev/null >${EXPLAIN_TMP_FILE}
-		tbl_updstats -d ${dbserver} -t ${tblname} ${low_mode_flag} ${resolution_clause_high} ${sampling_clause} ${resolution_clause_medium} ${confidence_clause} ${CMD_FLAGS}
+		tbl_updstats -d ${dbserver} -t ${tblname} ${ANSI_USER_CLAUSE}${low_mode_flag}${resolution_clause_high}${sampling_clause}${resolution_clause_medium}${confidence_clause}${CMD_FLAGS}
 		if [ "X${EXPLAIN_FLAG}" = "X1" ]
 		then
 			cat ${EXPLAIN_TMP_FILE} >>${explain_file}
@@ -634,7 +757,7 @@ do
 	X*)
 		#--- execute only
 		cat /dev/null >${EXPLAIN_TMP_FILE}
-		tbl_updstats -d ${dbserver} -t ${tblname} ${low_mode_flag} ${resolution_clause_high} ${sampling_clause} ${resolution_clause_medium} ${confidence_clause} ${CMD_FLAGS}
+		tbl_updstats -d ${dbserver} -t ${tblname} ${ANSI_USER_CLAUSE}${low_mode_flag}${resolution_clause_high}${sampling_clause}${resolution_clause_medium}${confidence_clause}${CMD_FLAGS}
 		if [ "X${EXPLAIN_FLAG}" = "X2" ]
 		then
 			cat ${EXPLAIN_TMP_FILE} >>${explain_file}
@@ -648,7 +771,7 @@ done <${TABLE_LIST_FILE}
 #-----------------------------------------------------
 if [ "X"$PROCEDURES_FLAG = "X1" ]
 then
-	echo "#${PROGNAME} Processing procedures at `date` ..."
+	echo "${COMMENT_STRING}${PROGNAME} Processing procedures at `date` ..."
 	case "X${EXPLAIN_FLAG}" in
 	X1)
 		EXPLAIN_CLAUSE="set explain on;"
@@ -658,6 +781,7 @@ then
 		;;
 	esac
 	dbaccess ${dbserver} <<!EOF 2>${SQL_ERROR_FILE} 1>${SQL_OUTPUT_FILE}
+${SET_AUTH_CLAUSE}
 ${EXPLAIN_CLAUSE}
 
 update statistics for procedure;
@@ -672,4 +796,4 @@ update statistics for procedure;
 		cat ${SQL_OUTPUT_FILE}
 	fi
 fi
-echo "#${PROGNAME} Ended at `date` ..."
+echo "${COMMENT_STRING}${PROGNAME} Ended at `date` ..."
diff --git a/scripts/updstats/tbl_updstats b/scripts/updstats/tbl_updstats
--- a/scripts/updstats/tbl_updstats
+++ b/scripts/updstats/tbl_updstats
@@ -46,12 +46,17 @@ show_help()
 	echo "               [-X] Display and execute" >&2
 	echo "               [-x] Display only. Don't execute" >&2
 	echo "               [-T] Include timings in de SQL generated" >&2
+	echo "               [-o user] define owner for ANSI databases" >&2
+	echo "               [-i] Set DIRTY READ isolation level" >&2
+	echo "               [-a] Database is ANSI (includes COMMIT after each UPD. STAT. cmd to avoid locking)" >&2
+	echo "               [-w N] Set LOCK MODE TO WAIT N seconds" >&2
+#	echo "               [-S user] SET SESSION AUTH TO user (run as...)" >&2
 
 }
 
 get_args()
 {
-	arg_ok="d:t:p:m:r:R:c:E:hleVTxX"
+	arg_ok="d:t:p:m:r:R:c:E:hleVTxXo:S:iaw:"
 	list="$*"
 	getopt ${arg_ok} $list >/dev/null 2>&1
 	# check result of parsing                                                
@@ -86,6 +91,12 @@ get_args()
 			explain_file=$2
 			shift
 			;;
+		-i)   # set up the -i (set DIRTY_READ flag)
+			DIRTY_READ_FLAG=1
+			;;
+		-a)   # set up the -i (set DIRTY_READ flag)
+			ANSI_FLAG=1
+			;;
 		-x)   # set up the -x (set DISPLAY_ONLY flag)
 			DISPLAY_FLAG=1
 			;;
@@ -107,6 +118,17 @@ get_args()
 			priority=$2
 			shift
 			;;
+		-w)   # set up the -w ( LOCK MODE flag)
+			LOCK_MODE_FLAG=1
+			LOCK_MODE_TIME=$2
+			echo ${LOCK_MODE_TIME} | grep "^[1-9][0-9]*" >/dev/null
+ 			if [ $? != 0  ]
+			then
+				echo "${PROGNAME} Syntax error: LOCK WAIT time must be between a number >= 1" >&2
+				return 1
+			fi
+			shift
+			;;
 		-m)   # set up the -m (sampling flag)
 			SAMPLING_FLAG=1
 			sampling=$2
@@ -125,6 +147,16 @@ get_args()
 		-c)   # set up the -c (confidence flag)
 			CONFIDENCE_FLAG=1
 			confidence=$2
+			shift
+			;;
+		-o)   # set up the -u (ANSI user flag)
+			ANSI_USER_FLAG=1
+			ANSI_USER=$2
+			shift
+			;;
+		-S)   # set up the -S (SET SESSION flag)
+			SET_AUTH_FLAG=1
+			SET_AUTH_USER=$2
 			shift
 			;;
 		esac
@@ -175,6 +207,24 @@ get_args()
 				return 1
 			else
 				LOW_MODE=1
+				shift
+			fi;;
+		-i)
+			if [ "X"$DIRTY_READ_FLAG != "X" ]	
+			then
+				echo "${PROGNAME}: Syntax error: DIRTY READ already processed" >&2
+				return 1
+			else
+				DIRTY_READ_FLAG=1
+				shift
+			fi;;
+		-a)
+			if [ "X"ANSI_FLAG != "X" ]	
+			then
+				echo "${PROGNAME}: Syntax error: ANSI flag already processed" >&2
+				return 1
+			else
+				ANSI_FLAG=1
 				shift
 			fi;;
 		-T)
@@ -246,6 +296,26 @@ get_args()
 					if [ ${priority} -lt 1 -o ${priority} -gt 100 ]
 					then
 						echo "Error: PDQPRIORITY value must be between 0 and 100" >&2
+						return 1
+					fi
+					shift 2
+			fi;;
+		-w)
+			if [ "X"$LOCK_MODE_FLAG = "X1" ]
+			then
+				echo "${PROGNAME} Syntax error: LOCK WAIT already processed" >&2
+				return 1
+			elif [ $# -le 1 ]
+				then
+					echo "${PROGNAME} Syntax error: Option $1 requires an argument" >&2
+					return 1
+				else
+					LOCK_MODE_FLAG=1
+					LOCK_MODE_TIME=$2
+					echo ${LOCK_MODE_TIME} | grep "^[1-9][0-9]*" >/dev/null
+ 					if [ $? != 0  ]
+					then
+						echo "${PROGNAME} Syntax error: LOCK WAIT time must be between a number >= 1" >&2
 						return 1
 					fi
 					shift 2
@@ -332,9 +402,39 @@ get_args()
 						
 						echo "Error: CONFIDENCE value must be between 0.80 and 0.99" >&2
 						return 1
-				fi
+					fi
 				shift 2
 			fi;;
+		-o)
+			if [ "X"$ANSI_USER_FLAG = "X1" ]
+			then
+				echo "Syntax error: ANSI user already processed" >&2
+				return 1
+			elif [ $# -le 1 ]
+				then
+					echo "Syntax error: Option $1 requires an argument" >&2
+					return 1
+				else
+					ANSI_USER_FLAG=1
+					ANSI_USER=$2
+			fi
+			shift 2
+			;;
+		-S)
+			if [ "X"$SET_AUTH_FLAG = "X1" ]
+			then
+				echo "Syntax error: SET AUTH already processed" >&2
+				return 1
+			elif [ $# -le 1 ]
+				then
+					echo "Syntax error: Option $1 requires an argument" >&2
+					return 1
+				else
+					SET_AUTH_FLAG=1
+					SET_AUTH_USER=$2
+			fi
+			shift 2
+			;;
 		*)
 			if [ "X"$DATABASE_FLAG != "X1" ]	
 			then
@@ -448,6 +548,33 @@ clean_up()
 }
 trap clean_up 0
  
+if [ "X"${ANSI_USER_FLAG} = "X1" ]
+then
+	ANSI_CLAUSE="and t.owner = '${ANSI_USER}'"
+else
+	ANSI_CLAUSE=""
+fi
+
+if [ "X${SET_AUTH_FLAG}" = "X1" ]
+then
+	SET_AUTH_CLAUSE="SET SESSION AUTHORIZATION TO '${SET_AUTH_USER}';"
+else
+	SET_AUTH_CLAUSE=""
+fi
+
+if [ "X${DIRTY_READ_FLAG}" = "X1" ]
+then
+	ISOLATION_CLAUSE="SET ISOLATION TO DIRTY READ;"
+else
+	ISOLATION_CLAUSE=""
+fi
+
+if [ "X${LOCK_MODE_FLAG}" = "X1" ]
+then
+	LOCK_MODE_CLAUSE="SET LOCK MODE TO WAIT ${LOCK_MODE_TIME};"
+else
+	LOCK_MODE_CLAUSE=""
+fi
 
 #--------------------------------------------------------
 # get the aux column files...
@@ -456,13 +583,17 @@ dbaccess ${DATABASE} 1>/dev/null 2>${SQL_ERROR_FILE} <<EOSQL
 -------------------------------------------------------
 -- find the index header columns
 -------------------------------------------------------
+$ISOLATION_CLAUSE
+$LOCK_MODE_CLAUSE
+$SET_AUTH_CLAUSE
 unload to ${IDX_HEADER_COLUMNS_FILE} delimiter ' '
 select unique trim(colname)
-from systables t, sysindexes i, syscolumns c
+from informix.systables t, informix.sysindexes i, informix.syscolumns c
 where tabname = '${tabname}' 
 and t.tabid = i.tabid
 and t.tabid = c.tabid
 and colno = abs(part1)
+$ANSI_CLAUSE
 order by 1;
 
 --------------------------------------------------------
@@ -470,38 +601,40 @@ order by 1;
 --------------------------------------------------------
 unload to ${NONINDEX_HEADER_COLUMNS_FILE} delimiter ' '
 select unique trim(colname)
-from syscolumns c, systables t
+from informix.syscolumns c, informix.systables t
 where c.tabid = t.tabid
 and t.tabname = '${tabname}'
-and c.colno not in ( select abs(i.part1) from sysindexes i where i.tabid = t.tabid)
+and c.colno not in ( select abs(i.part1) from informix.sysindexes i where i.tabid = t.tabid)
+$ANSI_CLAUSE
 order by 1;
 
 --------------------------------------------------------
 -- find the indexed columns
 --------------------------------------------------------
-select i.part1  part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid UNION
-select i.part2  part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid UNION
-select i.part3  part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid UNION
-select i.part4  part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid UNION
-select i.part5  part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid UNION
-select i.part6  part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid UNION
-select i.part7  part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid UNION
-select i.part8  part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid UNION
-select i.part9  part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid UNION
-select i.part10 part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid UNION
-select i.part11 part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid UNION
-select i.part12 part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid UNION
-select i.part13 part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid UNION
-select i.part14 part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid UNION
-select i.part15 part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid UNION
-select i.part16 part_x from sysindexes i, systables t where t.tabname = '${tabname}' and i.tabid = t.tabid
+select i.part1  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
+select i.part2  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
+select i.part3  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
+select i.part4  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
+select i.part5  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
+select i.part6  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
+select i.part7  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
+select i.part8  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
+select i.part9  part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
+select i.part10 part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
+select i.part11 part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
+select i.part12 part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
+select i.part13 part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
+select i.part14 part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
+select i.part15 part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid UNION
+select i.part16 part_x from informix.sysindexes i, informix.systables t where t.tabname = '${tabname}' $ANSI_CLAUSE and i.tabid = t.tabid
 into temp t_aux;
 
 unload to ${INDEXED_COLUMNS_FILE} delimiter ' '
 select unique trim(colname)
-from syscolumns c, systables t
+from informix.syscolumns c, informix.systables t
 where c.tabid = t.tabid
 and t.tabname = '${tabname}'
+$ANSI_CLAUSE
 and c.colno in (select abs(part_x)  from t_aux)
 order by 1;
 
@@ -510,9 +643,10 @@ order by 1;
 --------------------------------------------------------
 unload to ${NON_INDEXED_COLUMNS_FILE} delimiter ' '
 select unique trim(colname)
-from syscolumns c, systables t
+from informix.syscolumns c, informix.systables t
 where c.tabid = t.tabid
 and t.tabname = '${tabname}'
+$ANSI_CLAUSE
 and c.colno not in (select abs(part_x) from t_aux)
 order by 1;
 EOSQL
@@ -521,20 +655,40 @@ if [ $? != 0 ]
 then
 	printf "${PROGNAME} Error: dbaccess error when fetching column information for table ${DATABASE}@${INFORMIXSERVER}:${tabname}\n">&2
 	cat ${SQL_ERROR_FILE} >&2
+	echo $SET_AUTH_CLAUSE
 	exit 1
 fi
 
 #--------------------------------------------------------
 # start the SQL script preparation
 #--------------------------------------------------------
-echo > ${SQL_FILE}
+echo ""> ${SQL_FILE}
 OUTPUT_PREFIX=""
 #OUTPUT_PREFIX="${DATABASE}@${INFORMIXSERVER}:"
 printf "\n-- Update statistics for table ${DATABASE}@${INFORMIXSERVER}:${tabname}\n-- Generated by ${PROGNAME} ${VERSION} on `date` \n\n" >>${SQL_FILE}
 
+if [ "X${DIRTY_READ_FLAG}" = "X1" ]
+then
+	
+	printf "\n-- SET ISOLATION CLAUSE\n${ISOLATION_CLAUSE}\n" >> ${SQL_FILE}
+fi
+
+if [ "X${LOCK_MODE_FLAG}" = "X1" ]
+then
+	printf "\n-- SET LOCK MODE CLAUSE\n${LOCK_MODE_CLAUSE}\n" >> ${SQL_FILE}
+fi
+
+printf "\n${SET_AUTH_CLAUSE}\n" >>${SQL_FILE}
+
+if [ "X${ANSI_USER_FLAG}" = "X1" ]
+then
+	tabowner="\"$ANSI_USER\"."
+else
+	tabowner=""
+fi
 if [ "X${TIMINGS_FLAG}" = "X1" ]
 then
-	printf "\n-- Show stats timings\noutput to pipe 'grep -v \"^[ 	]*$\"' without headings select '${OUTPUT_PREFIX}${tabname} S: '||current year to fraction(3) from systables where tabid = 1;\n" >>${SQL_FILE}
+	printf "\n-- Show stats timings\noutput to pipe 'grep -v \"^[ 	]*$\"' without headings select '${OUTPUT_PREFIX}${tabowner}${tabname} S: '||current year to fraction(3) from informix.systables where tabid = 1;\n" >>${SQL_FILE}
 fi
 
 if [ "X${EXPLAIN_FLAG}" = "X1" ]
@@ -577,10 +731,10 @@ then
 	fi
 	if [ "X${TIMINGS_FLAG}" = "X1" ]
 	then
-		printf "\n-- Show stats timings\noutput to pipe 'grep -v \"^[ 	]*$\"' without headings select '${OUTPUT_PREFIX}${tabname} M: '||current year to fraction(3) from systables where tabid = 1;\n" >>${SQL_FILE}
+		printf "\n-- Show stats timings\noutput to pipe 'grep -v \"^[ 	]*$\"' without headings select '${OUTPUT_PREFIX}${tabowner}${tabname} M: '||current year to fraction(3) from informix.systables where tabid = 1;\n" >>${SQL_FILE}
 	fi
 
-	printf "\n-- MEDIUM distributions only for all columns that are not head of any index\nupdate statistics medium for table \"${tabname}\"\n    (" >>${SQL_FILE}
+	printf "\n-- MEDIUM distributions only for all columns that are not head of any index\nupdate statistics medium for table ${tabowner}\"${tabname}\"\n    (" >>${SQL_FILE}
 	FIRST=1
 	while read COLNAME
 	do
@@ -593,6 +747,10 @@ then
 		fi
 	done < ${NONINDEX_HEADER_COLUMNS_FILE}
 	printf  ")\n${sampling_clause}${resolution_clause_medium} distributions only;\n" >>${SQL_FILE}
+fi
+if [ "X${ANSI_FLAG}" = "X1" ]
+then
+	printf "\nCOMMIT;\n" >>${SQL_FILE}
 fi
  
 #-------------------------------------------------------
@@ -608,10 +766,10 @@ then
 	fi
 	if [ "X${TIMINGS_FLAG}" = "X1" ]
 	then
-		printf "\n-- Show stats timings\noutput to pipe 'grep -v \"^[ 	]*$\"' without headings select '${OUTPUT_PREFIX}${tabname} H: '||current year to fraction(3) from systables where tabid = 1;\n" >>${SQL_FILE}
+		printf "\n-- Show stats timings\noutput to pipe 'grep -v \"^[ 	]*$\"' without headings select '${OUTPUT_PREFIX}${tabowner}${tabname} H: '||current year to fraction(3) from informix.systables where tabid = 1;\n" >>${SQL_FILE}
 	fi
 
-	printf  "\n-- HIGH distributions only for all columns that are head of any index\nupdate statistics high for table \"${tabname}\"\n    (" >>${SQL_FILE}
+	printf  "\n-- HIGH distributions only for all columns that are head of any index\nupdate statistics high for table ${tabowner}\"${tabname}\"\n    (" >>${SQL_FILE}
 	FIRST=1
 	while read COLNAME
 	do
@@ -625,13 +783,18 @@ then
 	done <${IDX_HEADER_COLUMNS_FILE}
 	printf ")\n${resolution_clause_high} distributions only;\n" >>${SQL_FILE}
 fi
+if [ "X${ANSI_FLAG}" = "X1" ]
+then
+	printf "\nCOMMIT;\n" >>${SQL_FILE}
+fi
+
  
 #-------------------------------------------------------
 # Create sql statements for low 
 #-------------------------------------------------------
 if [ "X${TIMINGS_FLAG}" = "X1" ]
 then
-	printf "\n-- Show stats timings\noutput to pipe 'grep -v \"^[ 	]*$\"' without headings select '${OUTPUT_PREFIX}${tabname} L: '||current year to fraction(3) from systables where tabid = 1;\n" >>${SQL_FILE}
+	printf "\n-- Show stats timings\noutput to pipe 'grep -v \"^[ 	]*$\"' without headings select '${OUTPUT_PREFIX}${tabowner}${tabname} L: '||current year to fraction(3) from informix.systables where tabid = 1;\n" >>${SQL_FILE}
 fi
 
 case "X${LOW_MODE_FLAG}" in
@@ -639,7 +802,7 @@ X)
 	LINE_COUNT=`wc -l ${INDEXED_COLUMNS_FILE} | awk '{print $1}'`
 	if [ "X${LINE_COUNT}" != "X0" ]
 	then
-		printf  "\n-- LOW for all columns beloging to any index\nupdate statistics low for table \"${tabname}\"\n    (" >>${SQL_FILE}
+		printf  "\n-- LOW for all columns beloging to any index\nupdate statistics low for table ${tabowner}\"${tabname}\"\n    (" >>${SQL_FILE}
 		FIRST=1
 		while read COLNAME
 		do
@@ -653,14 +816,14 @@ X)
 		done <${INDEXED_COLUMNS_FILE}
 		printf ");\n\n" >>${SQL_FILE}
 	else
-		printf "\n-- LOW for table if table has no indexes\nupdate statistics low for table \"${tabname}\";\n\n" >>${SQL_FILE}
+		printf "\n-- LOW for table if table has no indexes\nupdate statistics low for table ${tabowner}\"${tabname}\";\n\n" >>${SQL_FILE}
 	fi
 	;;
 X1)
 	LINE_COUNT=`wc -l ${NON_INDEXED_COLUMNS_FILE} | awk '{print $1}'`
 	if [ "X${LINE_COUNT}" != "X0" ]
 	then
-		printf  "\n-- Using LOW quick mode... LOW for all columns NOT beloging to any index\nupdate statistics low for table \"${tabname}\"\n    (" >>${SQL_FILE}
+		printf  "\n-- Using LOW quick mode... LOW for all columns NOT beloging to any index\nupdate statistics low for table ${tabowner}\"${tabname}\"\n    (" >>${SQL_FILE}
 		FIRST=1
 		while read COLNAME
 		do
@@ -675,14 +838,19 @@ X1)
 		printf ");\n\n" >>${SQL_FILE}
 	else
 		COLNAME=`head -1 ${INDEXED_COLUMNS_FILE}`
-		printf "\n-- Using LOW quick mode, but all columns are indexed! Using just one column...\nupdate statistics low for table \"${tabname}\"( ${COLNAME} );\n\n" >>${SQL_FILE}
+		printf "\n-- Using LOW quick mode, but all columns are indexed! Using just one column...\nupdate statistics low for table${tabowner} \"${tabname}\"( ${COLNAME} );\n\n" >>${SQL_FILE}
 	fi
 	;;
 esac
 
+if [ "X${ANSI_FLAG}" = "X1" ]
+then
+	printf "\nCOMMIT;\n" >>${SQL_FILE}
+fi
+
 if [ "X${TIMINGS_FLAG}" = "X1" ]
 then
-printf "\n-- Show stats timings\noutput to pipe 'grep -v \"^[ 	]*$\"' without headings select '${OUTPUT_PREFIX}${tabname} E: '||current year to fraction(3) from systables where tabid = 1;\n" >>${SQL_FILE}
+printf "\n-- Show stats timings\noutput to pipe 'grep -v \"^[ 	]*$\"' without headings select '${OUTPUT_PREFIX}${tabowner}${tabname} E: '||current year to fraction(3) from informix.systables where tabid = 1;\n" >>${SQL_FILE}
 fi
 
 
