Verification if bc is available

diff --git a/scripts/ix/ixcaches b/scripts/ix/ixcaches
--- a/scripts/ix/ixcaches
+++ b/scripts/ix/ixcaches
@@ -2,8 +2,8 @@
 # Copyright (c) 2011-2016 Fernando Nunes - domusonline@gmail.com
 # License: This script is licensed as GPL V2 ( http://www.gnu.org/licenses/old-licenses/gpl-2.0.html )
 # $Author: Fernando Nunes - domusonline@gmail.com $
-# $Revision: 2.0.55 $
-# $Date: 2024-02-23 00:28:57 $
+# $Revision: 2.0.57 $
+# $Date: 2024-03-07 13:46:06 $
 # Disclaimer: This software is provided AS IS, without any kind of guarantee. Use at your own risk.
 #             Although the author is/was an IBM employee, this software was created outside his job engagements.
 #             As such, all credits are due to the author.
@@ -2595,7 +2595,7 @@ EOF
 #INIT
 
 PROGNAME=`basename $0`
-VERSION=`echo "$Revision: 2.0.55 $" | cut -f2 -d' '`
+VERSION=`echo "$Revision: 2.0.57 $" | cut -f2 -d' '`
 TMPFILE=/tmp/${PROGNAME}_$$.tmp
 ERRFILE=/tmp/${PROGNAME}_$$.err
 DATABASE_LIST=""
@@ -2609,6 +2609,12 @@ if [ $? != 0 ]
 then
 	ix_help >&2
 	exit 1
+fi
+which bc 2>/dev/null 1>&2
+if [ $? != 0 ]
+then
+        echo "Command bc not found. Exiting!" >&2
+        exit 1
 fi
 calc_dic_cache
 calc_dist_cache
