- Replaced several onstat -g act runs by a call to onstat -i to improve responsivness - Added option to select what sessions we want (based on thread status) - Added option to automatically run onstat -g ??? or ixses on the top sessions

diff --git a/scripts/ix/ixtop b/scripts/ix/ixtop
--- a/scripts/ix/ixtop
+++ b/scripts/ix/ixtop
@@ -8,15 +8,24 @@
 show_help()
 {
 	echo "${PROGNAME}:  ${PROGNAME} [ -h | -V ] | ">&2
-	echo "            [ -t <top_t_list> ] ">&2
-	echo "            [ [ -C ] [ -n <interactions> ] [ -c <min-runs> ] ]" >&2
-	echo "            [-H <bold>|<none>][ -p <part_order_by> [ -d <database_list> ] ]" >&2
-	echo "            [ -s | -l  <ses_order_by> [ -u <user_list> ] ]" >&2
-	echo "            [ -m ]" >&2
+	echo "  [-t <number>] [[ -C ] [-n <interactions>] [-c <min-runs>] [-r|-R|-I|-B|-L|-M|-E <regexp] [-e cmd [-f file]]]" >&2
+	echo "  [-t <number>] [-H <bold>|<none>][ -p <part_order_by> [ -d <database_list> ] ]" >&2
+	echo "  [-t <number>] [ -s | -l  <ses_order_by> [ -u <user_list> ] ]" >&2
+	echo "  [-t <number>] [ -m ]" >&2
 	echo " Where: " >&2
-	echo " -C : Get TOP cpu usage sessions">&2
-	echo "      -n <interactions>    : nuber of onstat -g act to trace [default=20]" >&2
+	echo " -t <number>               : limits the output to "number" of lines/objects" >&2
+	echo " -C : Get TOP sessions by condition">&2
+	echo "      -n <interactions>    : nuber of onstat -g ath to trace [default=20]" >&2
 	echo "      -c <min-runs>        : minimum ocurrences of the thread in the active list [default=2]" >&2
+	echo "      -r                   : running sessions" >&2
+	echo "      -R                   : running and ready sessions (default)" >&2
+	echo "      -I                   : IO Wait sessions" >&2
+	echo "      -B                   : bufwait sessions" >&2
+	echo "      -L                   : lockwait sessions" >&2
+	echo "      -M                   : mutex wait" >&2
+	echo "      -E <regexp>          : Whatever you want expressed as a regexp. Ex: (running|IO Wait)" >&2
+	echo "      -e <ses|sql|stm|stq|ixses> : executes the cmd command with SID as a parameter for each session found" >&2
+	echo "      -f <file>            : sends the output of cmd to the specified file">&2
 	echo " -p : Get TOP I/O, locks, lockwaits, buffer activity etc. per partition">&2
 	echo "      <database_list> : comma separated list of databases ">&2
 	echo "      <part_order_by> : field to order by: ">&2
@@ -43,7 +52,7 @@ show_version()
 }
 get_args()
 {
-	arg_ok="hVt:Cn:c:s:l:p:u:d:mH:"
+	arg_ok="hVt:Cn:c:s:l:p:u:d:mH:rRIBLME:e:f:"
 
 	while getopts ${arg_ok} OPTION
 	do
@@ -66,12 +75,101 @@ get_args()
 			TOP_SIZE=${OPTARG}
 			;;
 		C)     #flag for cpu TOP
-			if [ "X"${CPU_FLAG} = "X1" ]
+			if [ "X"${CONDITION_FLAG} = "X1" ]
 			then
 				echo "Error: Option ${OPTION} already processed" >&2
 				exit 1
 			fi
-			CPU_FLAG=1
+			CONDITION_FLAG=1
+			;;
+		r)	# running threads
+			if [ "X${THREAD_STATUS_FLAG}" = "X1" ]
+			then
+				echo "Error: Option to filter session status already processed" >&2
+				exit 1
+			fi
+			THREAD_STATUS_FLAG=1
+			THREAD_STATUS_EXPR=running
+			THREAD_DESC="sessions in running state"
+			;;
+		R)	# running and ready threads
+			if [ "X${THREAD_STATUS_FLAG}" = "X1" ]
+			then
+				echo "Error: Option to filter session status already processed" >&2
+				exit 1
+			fi
+			THREAD_STATUS_FLAG=1
+			THREAD_STATUS_EXPR="(running|ready)"
+			THREAD_DESC="sessions in running or ready state"
+			;;
+		I)	# IO Wait threads
+			if [ "X${THREAD_STATUS_FLAG}" = "X1" ]
+			then
+				echo "Error: Option to filter session status already processed" >&2
+				exit 1
+			fi
+			THREAD_STATUS_FLAG=1
+			THREAD_STATUS_EXPR="IO Wait"
+			THREAD_DESC="sessions in IO Wait state"
+			;;
+		B)	# bufwait threads
+			if [ "X${THREAD_STATUS_FLAG}" = "X1" ]
+			then
+				echo "Error: Option to filter session status already processed" >&2
+				exit 1
+			fi
+			THREAD_STATUS_FLAG=1
+			THREAD_STATUS_EXPR=bufwait
+			THREAD_DESC="sessions waiting for buffers"
+			;;
+		L)	# lock wait threads
+			if [ "X${THREAD_STATUS_FLAG}" = "X1" ]
+			then
+				echo "Error: Option to filter session status already processed" >&2
+				exit 1
+			fi
+			THREAD_STATUS_FLAG=1
+			THREAD_STATUS_EXPR=lockwait
+			THREAD_DESC="sessions waiting for locks"
+			;;
+		M)	# Mutex wait threads
+			if [ "X${THREAD_STATUS_FLAG}" = "X1" ]
+			then
+				echo "Error: Option to filter session status already processed" >&2
+				exit 1
+			fi
+			THREAD_STATUS_FLAG=1
+			THREAD_STATUS_EXPR="mutex wait"
+			THREAD_DESC="sessions in mutex wait"
+			;;
+		E)	# custom status
+			if [ "X${THREAD_STATUS_FLAG}" = "X1" ]
+			then
+				echo "Error: Option to filter session status already processed" >&2
+				exit 1
+			fi
+			THREAD_STATUS_FLAG=1
+			THREAD_STATUS_EXPR="$OPTARG"
+			THREAD_DESC="sessions in custom state expressed by regular expression: $THREAD_STATUS_EXPR"
+			;;
+		e)	# execute a command for each session
+			THREAD_CMD_FLAG=1
+			THREAD_CMD_EXE="$OPTARG"
+			echo $THREAD_CMD_EXE | egrep -e "^(ses|sql|stm|stq|ixses)$" >/dev/null
+			if [ $? != 0 ]
+			then
+				echo "Error: Invalid choice ($THREAD_CMD_EXE) for option -e" >&2
+				exit 1
+			fi
+			;;
+		f)	#Output file
+			THREAD_OUTPUT_FILE_FLAG=1
+			THREAD_OUTPUT_FILE=${OPTARG}
+			if [ ! -w ${THREAD_OUTPUT_FILE} -a ! -w `dirname ${THREAD_OUTPUT_FILE}` ]
+			then
+				echo "Error: Specified file (${THREAD_OUTPUT_FILE}) cannot be written to">&2
+				exit 1
+			fi
 			;;
 		H)     # highligth mode
 			if [ "X${HIGHLIGHT_FLAG}" = "X1" ]
@@ -283,22 +381,22 @@ get_args()
 			USER_LIST=${OPTARG}
 			;;
 		n)     #flag CPU number of onstat -g act INTERACTIONS
-			if [ "X${CPU_INTERACTIONS_FLAG}" = "X1" ]
+			if [ "X${CONDITION_INTERACTIONS_FLAG}" = "X1" ]
 			then
 				echo "Error: Option ${OPTION} already processed" >&2
 				exit 1
 			fi
-			CPU_INTERACTIONS_FLAG=1
-			CPU_INTERACTIONS=${OPTARG}
+			CONDITION_INTERACTIONS_FLAG=1
+			CONDITION_INTERACTIONS=${OPTARG}
 			;;
 		c)     #flag CPU minimum number of OCURRENCES
-			if [ "X"${CPU_MIN_OCURRENCES_FLAG} = "X1" ]
+			if [ "X"${CONDITION_MIN_OCURRENCES_FLAG} = "X1" ]
 			then
 				echo "Error: Option ${OPTION} already processed" >&2
 				exit 1
 			fi
-			CPU_MIN_OCURRENCES_FLAG=1
-			CPU_MIN_OCURRENCES=${OPTARG}
+			CONDITION_MIN_OCURRENCES_FLAG=1
+			CONDITION_MIN_OCURRENCES=${OPTARG}
 			;;
 		*)
 			echo "Error parsing arguments 1..." >&2
@@ -563,7 +661,7 @@ top_memory()
 	echo TOP memory not implemented yet... sorry!
 }
 
-top_cpu()
+top_condition()
 {
 	HOSTNAME=`hostname | cut -f1 -d'.'`
 
@@ -572,12 +670,13 @@ top_cpu()
 	CONT=1
 	while true
 	do
-		if [ ${CONT} -gt ${CPU_INTERACTIONS} ]
+		if [ ${CONT} -gt ${CONDITION_INTERACTIONS} ]
 		then
 			break
 		fi
-
-		onstat -g act | ${AWK} '$1 ~ "^ *[1-9]" {
+		echo ath
+		CONT=`expr $CONT + 1`
+	done | onstat -i |  egrep -e "$THREAD_STATUS_EXPR" | ${AWK} '$1 ~ "^ *[1-9]" {
 		if ( length($1) <=8 )
 		{
 			if ( $3 != 0) print $1 "|"
@@ -585,9 +684,8 @@ top_cpu()
 		else
 			if ($2 != 0 ) print substr($1,1,8) "|"
 		}' >> ${TEMP_FILE}
+#cat ${TEMP_FILE}
 
-		CONT=`expr $CONT + 1`
-	done
 
 	dbaccess sysmaster <<EOF 2>/dev/null
 
@@ -607,10 +705,39 @@ WHERE
 --	a.addresspad = b.scbpad AND
 	bitval(b.flags, '0x80000') = 1 AND
 	b.tid = x.col1
-	GROUP BY 2,3,4,5 HAVING COUNT(*)>=${CPU_MIN_OCURRENCES} ORDER BY 1 DESC
+	GROUP BY 2,3,4,5 HAVING COUNT(*)>=${CONDITION_MIN_OCURRENCES} ORDER BY 1 DESC
 EOF
+	if [ "X$THREAD_CMD_FLAG" = "X1" ]
+	then
+		if [ "X$THREAD_OUTPUT_FILE_FLAG" = "X" ]
+		then
+			THREAD_OUTPUT_FILE="/dev/tty"
+			printf "\n\n\n"
+		fi
+		if [ "X$THREAD_CMD_EXE" = "Xixses" ]
+		then
+			set -x
+			SESSION_LIST=""
+			head -${TOP_SIZE} ${TEMP_FILE} | while read DUMMY SID DUMMY1
+			do
+				SESSION_LIST="$SESSION_LIST $SID"
+			done
+			ixses $SESSION_LIST >$THREAD_OUTPUT_FILE
+			set +x
+		else
+			head -${TOP_SIZE} ${TEMP_FILE} | while read DUMMY SID DUMMY1
+			do
+				echo $THREAD_CMD_EXE $SID
+			done | onstat -i >$THREAD_OUTPUT_FILE
+		fi
+	fi
 
-	cat ${TEMP_FILE} | ${AWK} -v "PS_CMD=$PS_CMD" -v "HOSTNAME=$HOSTNAME" ' \
+	if [ "X$THREAD_STATUS_FLAG" = "X" ]
+	then
+		THREAD_DESC="sessions in running or ready state"
+	fi
+
+	cat ${TEMP_FILE} | ${AWK} -v "PS_CMD=$PS_CMD" -v "HOSTNAME=$HOSTNAME" -v "THREAD_DESC=$THREAD_DESC" ' \
 
 	BEGIN {
 		first=1;
@@ -618,6 +745,7 @@ EOF
 	{
 		if ( first == 1)
 		{
+			printf "Showing %s\n",THREAD_DESC;
 			printf "Seen  SessionID Username           PID    Hostname           Process\n";
 			printf "----- --------- ------------------ ------ ------------------ --------------------------------------------------\n";
 			first=0;
@@ -664,8 +792,8 @@ VERSION=`echo "$Revision$" | cut -f2 -d' '`
 TEMP_DIR=/tmp
 TEMP_FILE=${TEMP_DIR}/ixtop$$.tmp
 trap "rm -f ${TEMP_FILE}" 0
-CPU_INTERACTIONS=20
-CPU_MIN_OCURRENCES=2
+CONDITION_INTERACTIONS=20
+CONDITION_MIN_OCURRENCES=2
 TOP_SIZE=10
 
 get_args $*
@@ -711,14 +839,18 @@ else
 	FIRST_CLAUSE=""
 fi
 
-if [ "X${CPU_FLAG}" != "X1" -a  "X${SESSION_FLAG}" != "X1" -a "X${SESSION_L_FLAG}" != "X1" -a "X${MEMORY_FLAG}" != "X1" -a "X${PARTITION_FLAG}" != "X1" ]
+if [ "X${CONDITION_FLAG}" != "X1" -a  "X${SESSION_FLAG}" != "X1" -a "X${SESSION_L_FLAG}" != "X1" -a "X${MEMORY_FLAG}" != "X1" -a "X${PARTITION_FLAG}" != "X1" ]
 then
-	CPU_FLAG=1
+	CONDITION_FLAG=1
 fi
 
-if [ "X${CPU_FLAG}" = "X1" ]
+if [ "X${CONDITION_FLAG}" = "X1" ]
 then
-	top_cpu
+	if [ "X$THREAD_STATUS_FLAG" = "X" ]
+	then
+		THREAD_STATUS_EXPR="(running|ready)"
+	fi
+	top_condition
 fi
 
 if [ "X${SESSION_FLAG}" = "X1" ]
