- 11.50.xC3 does not include snmp dir. Created a list of optional dirs. If one of these is not found it warns instead of aborting

diff --git a/scripts/ix/ixvirtdir b/scripts/ix/ixvirtdir
--- a/scripts/ix/ixvirtdir
+++ b/scripts/ix/ixvirtdir
@@ -60,6 +60,7 @@ case $# in
 	exit 1
 esac
 
+OPTIONAL_DIRS="dummy"
 case $IX_VERSION in
 7)
 	IX_SUB_DIRS="aaodir bin dbssodir demo etc forms gls help incl ism lib msg release snmp"
@@ -76,6 +77,7 @@ case $IX_VERSION in
 11.5)
 	IX_SUB_DIRS="aaodir bin dbssodir demo doc etc extend forms gls help incl ism lib msg release snmp ids_license gskit gsk ssl tmp"
 	IX_DIRS="bin demo doc extend forms gls help incl ism lib msg release snmp ids_license gskit gsk"
+	OPTIONAL_DIRS=snmp
 	;;
 *)
 	echo "Version can only be 7, 9, 10, 11 or 11.5" >&2
@@ -140,8 +142,15 @@ for dir in $IX_SUB_DIRS
 do
 	if [ ! -d $EXISTING_IXDIR/$dir ]
 	then
-		echo "$EXISTING_IXDIR/$dir does not exist!... Aborting..." >&2
-		exit 1	
+		case $dir in
+		${OPTIONAL_DIRS})
+			echo "$EXISTING_IXDIR/$dir does not exist!... Skiping..." >&2
+			;;
+		*)
+			echo "$EXISTING_IXDIR/$dir does not exist!... Aborting..." >&2
+			exit 1
+			;;
+		esac
 	fi
 done
 
