- Verified for v11. Gives error if groups are given and if it's run with informix and informix does not belong to one of the groups.

diff --git a/scripts/ix/ixvirtdir b/scripts/ix/ixvirtdir
--- a/scripts/ix/ixvirtdir
+++ b/scripts/ix/ixvirtdir
@@ -25,50 +25,12 @@ case $# in
 	EXISTING_IXDIR=$1
 	NEW_IXDIR=$2
 	IX_VERSION=$3
-	case $IX_VERSION in
-	7)
-		IX_SUB_DIRS="aaodir bin dbssodir demo etc forms gls help incl ism lib msg release snmp"
-		IX_DIRS="bin demo forms gls help incl ism lib msg release snmp"
-		;;
-	9)
-		IX_SUB_DIRS="aaodir bin dbssodir demo doc etc extend forms gls help incl ism lib msg release snmp"
-		IX_DIRS="bin demo doc extend forms gls help incl ism lib msg release snmp"
-		;;
-	10)
-		IX_SUB_DIRS="aaodir bin dbssodir demo doc etc extend forms gls help incl ism lib msg release snmp ids_license master_license"
-		IX_DIRS="bin demo doc extend forms gls help incl ism lib msg release snmp ids_license master_license"
-		;;
-	*)
-		echo "Version can only be 7, 9 or 10" >&2
-		usage
-		exit 1
-		;;
-	esac
 	GROUPS_FLAG=0
 	;;
 6)
 	EXISTING_IXDIR=$1
 	NEW_IXDIR=$2
 	IX_VERSION=$3
-	case $IX_VERSION in
-	7)
-		IX_SUB_DIRS="aaodir bin dbssodir demo etc forms gls help incl ism lib msg release snmp"
-		IX_DIRS="bin demo forms gls help incl ism lib msg release snmp"
-		;;
-	9)
-		IX_SUB_DIRS="aaodir bin dbssodir demo doc etc extend forms gls help incl ism lib msg release snmp"
-		IX_DIRS="bin demo doc extend forms gls help incl ism lib msg release snmp"
-		;;
-	10)
-		IX_SUB_DIRS="aaodir bin dbssodir demo doc etc extend forms gls help incl ism lib msg release snmp ids_license master_license"
-		IX_DIRS="bin demo doc extend forms gls help incl ism lib msg release snmp ids_license master_license"
-		;;
-	*)
-		echo "Version can only be 7, 9 or 10" >&2
-		usage
-		exit 1
-		;;
-	esac
 	DBSA_GROUP=$4
 	grep "^${DBSA_GROUP}:" /etc/group 1>/dev/null 2>/dev/null
 	if [ $? != 0 ]
@@ -97,13 +59,37 @@ case $# in
 	exit 1
 esac
 
-SO=`uname -s | tr "[A-Z]" "[a-z]"`
+case $IX_VERSION in
+7)
+	IX_SUB_DIRS="aaodir bin dbssodir demo etc forms gls help incl ism lib msg release snmp"
+	IX_DIRS="bin demo forms gls help incl ism lib msg release snmp"
+	;;
+9)
+	IX_SUB_DIRS="aaodir bin dbssodir demo doc etc extend forms gls help incl ism lib msg release snmp"
+	IX_DIRS="bin demo doc extend forms gls help incl ism lib msg release snmp"
+	;;
+10|11)
+	IX_SUB_DIRS="aaodir bin dbssodir demo doc etc extend forms gls help incl ism lib msg release snmp ids_license master_license"
+	IX_DIRS="bin demo doc extend forms gls help incl ism lib msg release snmp ids_license master_license"
+	;;
+*)
+	echo "Version can only be 7, 9, 10 or 11" >&2
+	usage
+	exit 1
+	;;
+esac
+SO=`uname -s | tr "[:upper:]" "[:lower:]"`
 case $SO in
-sunos*|osf*)
+sunos*)
         AWK=nawk
+	export AWK
+	GROUP_MEMBERSHIP=`id -a | ${AWK} -F'=' '{print $4}' | ${AWK} -F'[()]' '{for (f=2;f<NF;f=f+2) {printf "%s|",$f}print""}'`
         ;;
 linux|*)
         AWK=awk
+	export AWK
+	ID_FLAGS=
+	GROUP_MEMBERSHIP=`id | ${AWK} -F'=' '{print $4}' | ${AWK} -F'[()]' '{for (f=2;f<NF;f=f+2) {printf "%s|",$f}print""}'`
         ;;
 esac
 
@@ -111,8 +97,24 @@ export AWK
 
 MY_USER=`id | ${AWK} -F"[()]" ' { print $2 } '`
 
+
+
 case $MY_USER in
-informix|root)
+root)
+	;;
+informix)
+	if [ "X${GROUPS_FLAG}" = "X1" ]
+	then
+		WARN_FLAG=0
+		for GROUP in $DBSA_GROUP $AAO_GROUP $DBSSO_GROUP
+		do
+			echo $GROUP_MEMBERSHIP | grep "$GROUP|" >/dev/null
+			if [ $? != 0 ]
+			then
+				WARN_FLAG=1
+			fi
+		done
+	fi
         ;;
 *)
         echo "This utility must be run as root or informix" >&2
@@ -184,17 +186,28 @@ then
 		chown informix:informix $NEW_IXDIR/dbssodir
 		chown informix:informix $NEW_IXDIR/etc
 		chown informix:informix $NEW_IXDIR/aaodir
-	else
-		if [ "X${GROUPS_FLAG}" = "X1" ]
-		then
-			chown informix:${DBSSO_GROUP} $NEW_IXDIR/dbssodir
-			chown informix:${DBSA_GROUP} $NEW_IXDIR/etc
-			chown informix:${AAO_GROUP} $NEW_IXDIR/aaodir
-		else
-			echo "Internal error: Invalid value for GROUPS_FLAG..." >&2
-			exit 1
-		fi
 	fi
 fi
+
+if [ "X${GROUPS_FLAG}" = "X1" ]
+then
+	if [ "X${WARN_FLAG}" = "X0" ]
+	then
+		chown informix:${DBSSO_GROUP} $NEW_IXDIR/dbssodir
+		chown informix:${DBSA_GROUP} $NEW_IXDIR/etc
+		chown informix:${AAO_GROUP} $NEW_IXDIR/aaodir
+	else
+		echo "User does not belong to all the specified groups"
+		echo "These commands will have to be run by root:"
+
+		echo chown informix:${DBSSO_GROUP} $NEW_IXDIR/dbssodir
+		echo chown informix:${DBSA_GROUP} $NEW_IXDIR/etc
+		echo chown informix:${AAO_GROUP} $NEW_IXDIR/aaodir
+	fi
+else
+	echo "Internal error: Invalid value for GROUPS_FLAG..." >&2
+	exit 1
+fi
+
 chmod 770 dbssodir aaodir
 chmod 775 etc
